### PR TITLE
Update requirements from get.typo3.org

### PR DESCRIPTION
**Pull request by gilbertsoft**
~~Live demo available at https://7ba9ac64.ngrok.io/doc-install/In-depth/SystemRequirements/Index.html~~

Demo is not longer available

### CODE REVIEW

**Comment by sypets** [comment]
Ok, so you are retrieving some information dynamically via JavaScript from get.typo3.org and defined textroles for that. Did you talk with Martin / Benji about that? If we do it that way, that is something that should probably go in the theme. I would like to leave it to those 2 to make a statement as to if this is the way we should go.

**Comment by marble** [comment]
Well, great idea to ask get.typo3.org. However, having that dynamically AT READ TIME would be an unexpected paradigm shift that's incompatible with user expectations, indexing, search, and the general idea of Sphinx documentation being *not only html* but other formats as well.

But still it could be done smoothly. For example by means of a Sphinx extensions, that generates the proper information AT RENDERING TIME and provides that either as reST source for an `.. include::` or as some magic variable `|t3…|` like Sphinx already has `|today|` or `|version|`.

With `.. include::` probably being the better and more flexible and self-documenting solution.
Thinking about this: This could be done VERY EASY as one step in the toolchain of the container.

Is the REST api of get.typo3.org documented? The main task would be to think about what information be should request and how should it be presented in reST and the rendered manuals.

**Comment by gilbertsoft** [comment]
I'll repeat my comment from Slack: idea is to always have an up to date information about the sys reqs which lacks sometimes currently. In the first place the docs should be up to date of course but if not it gets overriden by the information from get.t3o. This will give you some time to update the information here and doesn't make changes urgent.

**Comment by gilbertsoft** [comment]
API Doc https://get.typo3.org/v1/api/doc

**Comment by gilbertsoft** [comment]
Request example `https://get.typo3.org/v1/api/major/10/requirements`

**Comment by sypets** [comment]
This is currently marked as draft. Is this PR ready for review?

**Comment by gilbertsoft** [comment]
No, this was the first try but should be rewritten now as proposed by @marble

**Comment by sypets** [comment]
> No, this was the first try but should be rewritten now as proposed by @marble

I will close now. Please reopen or create new PR when ready.

**Pull request closed without merging**
