### PR TITLE
[TASK] Describe migrating assets to public/_assets

### PR DESCRIPTION
**Pull request by garvinhicking**
Mostly taken from the improved ChangeLog of the TYPO3 core, with some Sphinx-rendering adaptations and a crosslink.

Exact differences from the merged Changelog https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Important-98484-ExtensionsOutsideOfDocumentRootForComposer-basedTYPO3Installations.html#important-98484-1664553704 are:

* Use ":html:" instead of ":fluid:" (does not exist in Sphinx)
* Use ":html:" instead of ":css:" (doesn ot exist in Sphinx)
* Reference the "cms-composer-installers" Link
* Refrence helhum/typo3-console
* Reference ChangeLog entry
* Remove "impact" headline, use "migration" instead. Add a paragraph with a short intro.

Once this is merged, we can link to it from:

https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/DirectoryStructure/Index.html#file-public-assets

References https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/920

Releases: main, 12.4

### CODE REVIEW

**Review by linawolf — APPROVED** [review]

**Comment by linawolf** [comment]
I switched to the new rendering, so you can rebase and apply the needed changes right away.

**Comment by brotkrueml** [comment]
Will have a look, but not today.

**Comment by garvinhicking** [comment]
@brotkrueml Thank you; yes, I already planned to wait for you before merging. Take your time - I'll rebase this to new rendering first then, as well.

**Review by jonaseberle — APPROVED** [review]

**Comment by brotkrueml** [comment]
@garvinhicking Can you resolve the conflict? Then I will look at the PR.

**Review by froemken — APPROVED** [review]
Very good information. Thank you.

**Pull request merged**
