### PR TITLE
Fix sentence

### PR DESCRIPTION
**Pull request by remonator**
It's either "a great number of" or "many" - feel free to adjust.

### CODE REVIEW

**Comment by mbrodala** [comment]
Since "great" tends to have a negative touch nowadays, "many" should be fine. ;-)

**Comment by sypets** [comment]
Since we don't use many database systems but we use one of many, maybe a slightly different phrase is better.

Intuitively, I would use "many different". But, I am not a native speaker. I can look this up ....

**Comment by sypets** [comment]
Or just:

> TYPO3 can be used with the following database systems: MariaDB etc.

**Comment by remonator** [comment]
How about

> TYPO3 works with several database systems: [list]

**Comment by sypets** [comment]
sorry, did not see this was already merged. The original change was fine. 

The rest was fine-tuning and optimization which - to choose the best option I would prefer the vote of a native speaker. So, if someone would like to continue, you are welcome, but you must create a new patch.

**Pull request merged**
