### PR TITLE
[FEATURE] Add hint for getting list of system extensions

### PR DESCRIPTION
**Pull request by sypets**

### CODE REVIEW

**Comment by sypets** [comment]
@koehnlein Can you take a look?

**Comment by koehnlein** [comment]
First of all, thanks for that additional hint! I think it, could be helpful for advanced users. But I'm not happy with the position as the very first migration step.
The tutorial was meant as a composer beginner tutorial, when I created it. On the one hand, it's correct to get the list of installed sysexts, before you start to migrate your project. On the other hand, I think it would be better to not confuse composer beginners with concepts like "subtree split" in the very first migration step. At the moment, "subtree split" is mentioned a few steps later ([The new way: add only code, you need](https://docs.typo3.org/typo3cms/InstallationGuide/MigrateToComposer/MigrationSteps.html#the-new-way-add-only-code-you-need))

I think, it would fit better in the "Best practice" section. What do you think?

**Comment by sypets** [comment]
@koehnlein Hmm, I agree: it's a good idea to not throw too many new concepts at people right at the beginning. On the other hand, I think it would be a good idea to create the list of system extensions before they trash their installation. They can always add more as they go along, but I found it a little tedious to go through the list and require further sysexts manually. I used the list and added require in a loop. Made it easier for me.

I'll think about it some more. Maybe we can come up with a better idea to do this.

Anyway, I am currently using your instructions myself. I find it very useful and so far everything works great by using the instructions (not done yet). Thanks for submitting it!

Question:
* Is the "subtree split" explained somewhere where we could link to (I'll also check myself)?

**Comment by koehnlein** [comment]
The best "subtree split" explanation, I found so far, is https://usetypo3.com/typo3-subtree-split-and-composer.html

**Comment by sypets** [comment]
Thanks. usetypo3.com has very good explanations.

Ok. I'll close this for now, maybe we can talk on Slack if there is anything else ...

**Pull request closed without merging**
