### PR TITLE
Wrong System Requirement

### PR DESCRIPTION
**Pull request by maltisch**
Updated wrong system requirement. from MySQL5.7 to  MySQL 5.5

### CODE REVIEW

**Comment by gilbertsoft** [comment]
@maltisch Thanks for your proposition. You currently try to change the master which is in fact TYPO3 11.0 and to be released end of the year. The requirements are not defined at moment and imho this change makes no sense before we released v11. Please check you select the right version at docs.typo3.org to see the correct requirements for your version. And BTW we try to keep the requirements up to date at https://get.typo3.org for each major version.

**Comment by sypets** [comment]
@gilbertsoft The differences between versions for MySQL do not just apply to master, but also to 10.4 and 9.5:

10.4 

* Install Guide: MySQL >= 5.7 <= 8.1
* get.typo3.org: MySQL 5.5+

9.5 
* Install Guide: MySQL >= 5.0 <= 5.7,
* get.typo3.org: MySQL 5.5+

8.7 looks ok: 
* Install Guide: >= 5.0 <= 5.7 
* get.typo3.org: MySQL 5.0 ... 5.7

When we get a change like this, we usually merge it into master and backport it to 10.4. That means master and 10.4 would get the same change until 11 is released and there are differences. 

I am reluctant to merge anything concerning system requirements currently, because I don't know what the authoritative source is. If someone can confirm what is the correct database versions currently for master, 10.4 and 9.5 I would be happy to merge / make the necessary changes myself.

**Comment by sypets** [comment]
Posted question in Slack channel: https://typo3.slack.com/archives/C03AM9R17/p1601912805110800

**Comment by sypets** [comment]
I posted question in Slack, because I was not sure which system requirements to use, currently, see https://typo3.slack.com/archives/C03AM9R17/p1601912805110800


> According to DBAL we currently support MySQL 5.0+, 5.7.9+ and 8.0+ see https://www.doctrine-project.org/projects/doctrine-dbal/en/2.10/reference/platforms.html#mysql so the information at get.t3o is still correct but a little bit pessimistic as versions below 5.5 are not listed. But this is not tested at Bamboo at all,

To not make this more complicated, I suggest to use what get.typo3.org lists.

**Pull request merged**
