### PR TITLE
Added Links

### PR DESCRIPTION
**Pull request by ursbraem**
I've added two links to walkthroughs about 6.2 upgrade, one by myself

### CODE REVIEW

**Comment by xperseguers** [comment]
Looks like a list by reading, why are bullet points not included and merge was performed? :)

**Comment by marble** [comment]
Thank you ursbraem. I've edited the text to make it work and fit better. See 
 file:///home/marble/Repositories/github.com/TYPO3-Documentation/TYPO3CMS-Guide-Installation/Documentation/_make/build/html/Upgrade/Index.html

**Comment by ursbraem** [comment]
Hi marble, thanks! Sorry for the missing bullets. But would it be ok if we put it into a "note" box? It's easily overread now. Actually, I had to look at the page 5 times to see the change, albeit knowing it should be there. Btw. are there any other known sources?

**Comment by marble** [comment]
Hi Urs, for your info: I had added the bullets, the underscores at the end to make that links and there isn't an admonition ".. Links::" so that didn't work. Yes, it can be a bit confusing, as crossreferencing with the ":ref:`abc`" textrole doesn't have underscores at the end. I don't think the links should appear in a "note" admonition as they are normal content and maybe others want to add to it. But, yes, picking up your wish: It makes sense to make the links better visible and move them to the top. Can you live with that? Refresh your browser! Martin

**Comment by ursbraem** [comment]
Hey super, thanks!! Have a nice day.

**Pull request merged**
