### PR TITLE
[TASK] update Index.rst to reflect TYPO3 CMS 7 LTS version number

### PR DESCRIPTION
**Pull request by schams-net**
These changes take TYPO3 CMS version 7.6.x into account (TYPO3 CMS 7 LTS).

### CODE REVIEW

**Comment by marble** [comment]
Hi Michael, before we start checking this in: Should we create a 6.2 branch first? I'm justing asking, I didn't look into the manual

**Comment by schams-net** [comment]
Hi Martin. If a 6.2 branch is required to be able to switch between 6.2 and 7.x docs, then yes, that would be great.

My pull-request originates from a discussion on the [typo3-german mailing list](http://lists.typo3.org/pipermail/typo3-german/2016-January/114625.html) where someone (quite rightly) complained, that the installation guide only refers to TYPO3 CMS 6.2.

**Comment by pgampe** [comment]
@marble did you close this by intention? The patch has not been merged so far.

**Comment by marble** [comment]
We have the new branches 6.2 and 7.6 now. I have removed this brach named "typo3-cms-7.6", as it doesn't follow our naming convention. This patch has been applied to branches 7.6 and "latest", although it's not perfect for "latest". So "latest" could still be improved.

**Comment by pgampe** [comment]
OK thanks, this was not obvious from the issue ;)

**Pull request closed without merging**
