### PR TITLE
[TASK] Add vendor folder symlink for non installation installation

### PR DESCRIPTION
**Pull request by sbusemann**

### CODE REVIEW

**Review by linawolf — APPROVED** [review]

**Comment by linawolf** [comment]
backport: master, 10.4, 9.5

**Comment by jonaseberle** [comment]
Does linking `typo3_src/vendor` fix a known problem? IMHO that is not necessary.

**Comment by mbrodala** [comment]
Yes, it's not necessary. If you get an error, you should ask about it in the TYPO3 Slack since there's very likely something wrong.

@linawolf We should revert this change since it is not necessary.

**Comment by linawolf** [comment]
It is reverted

**Comment by sbusemann** [comment]
@mbrodala @linawolf  please follow the steps of https://docs.typo3.org/m/typo3/guide-installation/10.4/en-us/QuickInstall/GetAndUnpack/Index.html

You end up with the following structure of files:
typo3_src-10.4.x/
public/typo3_src -> ../typo3_src-10.4.x/
public/typo3 -> typo3_src/typo3/
public/index.php -> typo3_src/index.php

The Backend will work. The frontend won't work.

index.php will try to:

call_user_func(function () {
    $classLoader = require dirname(__DIR__).'/vendor/autoload.php';


which is not there.

**Comment by sbusemann** [comment]
Ok I found the problem. My error occurs, if you copy the index.php (what is needed at a domainfactory server). Then the vendor folder must be symlinked or index.php must be adjusted.

**Pull request merged**
